name: Style Check
on:
  push:
    branches:
      - master

jobs:
  unity:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone repo
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: C# Check Style
        run: |
          dotnet tool install --global dotnet-format
          dotnet format --check