name: StyleCop

on:
  push:
    branches:
      - master

jobs:
  unity:
    runs-on: windows-latest  # Используем образ Windows для поддержки .NET Framework

    steps:
      - name: Git clone repo
        uses: actions/checkout@v2

      - name: Setup .NET Framework
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '4.7.1'

      - name: Install StyleCop.Analyzers
        run: |
          dotnet add package StyleCop.Analyzers --version 1.1.118
          dotnet restore Assembly-CSharp.csproj

      - name: C# Check Style
        run: |
          dotnet build
          dotnet stylecop