name: StyleCop

on:
  push:
    branches:
      - master

jobs:
  unity:
    runs-on: windows-latest

    steps:
      - name: Git clone repo
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install StyleCop.Analyzers
        run: |
          dotnet add package StyleCop.Analyzers --version 1.1.118
          dotnet restore Assembly-CSharp.csproj

      - name: Unity Install
        run: |
          dotnet add package StyleCop.Analyzers --version 1.1.118
          dotnet restore Assembly-CSharp.csproj

      - name: C# Check Style
        run: |
          dotnet build /p:StyleCopEnabled=true